/**
 * NFA PASSBOOK — QR Code Generation & Print Layouts (ID Cards + A4 Reports)
 */
function buildQrPayload(farmer) {
  return JSON.stringify({
    serial: farmer.passbook_id,
    type: farmer.passbook_type === 'Master' ? 'MB' : 'FB',
    rsbsa: farmer.rsbsa_no,
    name: [farmer.first_name, farmer.middle_name, farmer.last_name].filter(Boolean).join(' '),
    org: farmer.farmer_org || ''
  });
}

/** Renders a QR code into a DOM element using the qrcodejs library. */
function renderQrInto(el, text, size = 180) {
  el.innerHTML = '';
  // eslint-disable-next-line no-undef
  new QRCode(el, {
    text,
    width: size,
    height: size,
    colorDark: '#000000',
    colorLight: '#ffffff',
    correctLevel: QRCode.CorrectLevel.H
  });
}

/** Waits for every <img> inside a container to finish loading (or fail) —
 *  printing before the logo image has loaded would leave it blank/broken. */
function waitForImages(container) {
  const imgs = Array.from(container.querySelectorAll('img'));
  return Promise.all(imgs.map(img => {
    if (img.complete) return Promise.resolve();
    return new Promise(resolve => {
      img.addEventListener('load', resolve, { once: true });
      img.addEventListener('error', resolve, { once: true });
    });
  }));
}

async function printPassbookId(farmer) {
  const settings = await getAllSettings();
  const printArea = document.getElementById('print-area');
  const name = buildDisplayName(farmer);
  const typeLabel = farmer.passbook_type === 'Master' ? 'MASTER / FO' : 'INDIVIDUAL FARMER';
  const birthDateFormatted = formatDateOnly(farmer.birth_date);

  printArea.innerHTML = `
    <div class="id-print-wrap">
      <div class="id-card">
        <div class="id-card-accent"></div>
        <div class="id-header">
          <img class="seal-logo" src="icons/nfa-official-logo.png" alt="NFA" width="42" height="42">
          <div class="txt"><b>NATIONAL FOOD AUTHORITY</b>REGION ${settings.REGION_CODE} · ${(settings.BRANCH_NAME || '').toUpperCase()} BRANCH</div>
          <div class="type-ribbon">${typeLabel}</div>
        </div>
        <div class="id-body">
          <div class="id-left">
            <span class="id-name">${name}</span>
            <div class="id-row"><span class="k">RSBSA No.</span><span class="v">${farmer.rsbsa_no || '—'}</span></div>
            <div class="id-row"><span class="k">Birthday</span><span class="v">${birthDateFormatted}</span></div>
            <div class="id-row"><span class="k">Farm Addr.</span><span class="v">${farmer.farm_municipality}, ${farmer.farm_province}</span></div>
            <div class="id-row"><span class="k">Land Area</span><span class="v">${formatComma(farmer.hectarage)} Ha · ${farmer.irrigated === 'Yes' ? 'Irrigated' : 'Rainfed'}</span></div>
          </div>
          <div class="id-right">
            <div id="id-qr-host"></div>
          </div>
        </div>
        <div class="id-footer">
          <span class="serial">${farmer.passbook_id}</span>
        </div>
      </div>
    </div>
  `;

  renderQrInto(document.getElementById('id-qr-host'), buildQrPayload(farmer), 100);

  await waitForImages(printArea);
  setTimeout(() => window.print(), 150);
}

/** Prints a full-page A4 report given a title and an HTML table body. */
function printReport(title, subtitle, tableHtml) {
  const printArea = document.getElementById('print-area');
  const now = new Date();
  printArea.innerHTML = `
    <div class="report-page">
      <div class="report-header">
        <img class="report-logo" src="icons/nfa-official-logo.png" alt="NFA" width="52" height="52">
        <div class="report-header-text">
          <div class="report-agency">NATIONAL FOOD AUTHORITY</div>
          <div class="report-title">${title}</div>
          <div class="report-subtitle">${subtitle}</div>
        </div>
        <div class="report-date-stamp">
          <div class="report-date-label">Generated</div>
          <div class="report-date-value">${now.toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</div>
          <div class="report-date-value">${now.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</div>
        </div>
      </div>
      <div class="report-table-wrap">${tableHtml}</div>
      <div class="report-signoff">
        <div class="report-signoff-block">
          <div class="report-signoff-line"></div>
          <div class="report-signoff-label">Prepared By</div>
        </div>
        <div class="report-signoff-block">
          <div class="report-signoff-line"></div>
          <div class="report-signoff-label">Noted By</div>
        </div>
      </div>
      <div class="report-footer">National Food Authority — ${title} — Page auto-generated by NFA Passbook</div>
    </div>
  `;
  setTimeout(() => window.print(), 150);
}
